#!/usr/bin/env python3
"""
VC Portfolio Job Monitor (Supabase Edition)
==============================================
Monitors VC portfolio pages for companies at Series A / B / C.
Scrapes job listings for leadership finance & operations titles.
Tracks new portfolio additions and removes companies that raise Series D+.

Output columns: Title | Company | Stage | VCs Invested | Location | Salary | Job URL

Supabase Database Schema
------------------------
CREATE TABLE vc_portfolio_companies (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company text NOT NULL,
  domain text UNIQUE,
  stage text,
  vc_names jsonb,
  vc_contact text,
  careers_url text,
  ats_type text,
  ats_slug text,
  active boolean DEFAULT true,
  excluded boolean DEFAULT false,
  first_seen timestamptz,
  last_seen timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE vc_jobs (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  company_id bigint REFERENCES vc_portfolio_companies(id),
  title text,
  url text UNIQUE,
  location text,
  salary_text text,
  salary_min integer,
  vc_names jsonb,
  source text DEFAULT 'vc_monitor',
  first_seen timestamptz,
  last_seen timestamptz,
  active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE vc_scan_log (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  vc_name text,
  scanned_at timestamptz,
  companies_found integer,
  status text,
  created_at timestamptz DEFAULT now()
);

Setup
-----
    pip install requests beautifulsoup4 lxml playwright
    playwright install chromium          # for JS-heavy VC portfolio pages

Usage
-----
    python vc_monitor.py --all           # full pipeline (scan VCs → find careers → scan jobs → report)
    python vc_monitor.py --scan-vcs      # only refresh VC portfolio company list
    python vc_monitor.py --find-careers  # only discover careers pages
    python vc_monitor.py --scan-jobs     # only pull current job listings
    python vc_monitor.py --report        # re-export last results without re-scanning
    python vc_monitor.py --test-ats greenhouse:lever lever:levels ashby:ashbyhq
                                         # quick test of specific ATS slugs
"""

import argparse
import asyncio
import json
import logging
import os
import re
import time
from datetime import datetime
from pathlib import Path
from typing import Optional
from urllib.parse import urljoin, urlparse

import requests
from bs4 import BeautifulSoup

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)-8s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────
# SUPABASE CONFIGURATION
# ─────────────────────────────────────────────────────────────────────

SUPABASE_URL = os.environ.get(
    "SUPABASE_URL",
    "https://jhreeyesdtnmanolmjqu.supabase.co/rest/v1",
)
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "")


class SupabaseClient:
    """Simple Supabase REST client for VC monitor operations."""

    def __init__(self, url: str = SUPABASE_URL, key: str = SUPABASE_KEY):
        self.url = url
        self.headers = {
            "apikey": key,
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
        }

    def select(self, table: str, query: str = "", limit: int = 1000) -> list[dict]:
        """GET from table with optional filter query."""
        url = f"{self.url}/{table}"
        params = {"limit": limit}
        if query:
            params["select"] = query
        try:
            resp = requests.get(url, headers=self.headers, params=params, timeout=15)
            resp.raise_for_status()
            return resp.json() if resp.text else []
        except Exception as e:
            log.debug(f"Supabase SELECT {table} failed: {e}")
            return []

    def select_where(self, table: str, filters: dict, limit: int = 1000) -> list[dict]:
        """GET with WHERE conditions (filter via query params)."""
        url = f"{self.url}/{table}"
        params = {"limit": limit}
        for key, val in filters.items():
            if isinstance(val, bool):
                params[f"{key}=eq.{str(val).lower()}"] = None
            elif isinstance(val, str):
                params[f"{key}=eq.{val}"] = None
            else:
                params[f"{key}=eq.{val}"] = None

        try:
            resp = requests.get(url, headers=self.headers, params=params, timeout=15)
            resp.raise_for_status()
            return resp.json() if resp.text else []
        except Exception as e:
            log.debug(f"Supabase SELECT {table} with filters failed: {e}")
            return []

    def insert(self, table: str, data: dict | list[dict]) -> bool:
        """POST to insert new rows."""
        url = f"{self.url}/{table}"
        try:
            headers = self.headers.copy()
            headers["Prefer"] = "return=minimal"
            resp = requests.post(url, json=data, headers=headers, timeout=15)
            resp.raise_for_status()
            return True
        except Exception as e:
            log.warning(f"Supabase INSERT {table} failed: {e}")
            try:
                log.warning(f"  Response body: {resp.text[:500]}")
            except Exception:
                pass
            return False

    def upsert(self, table: str, data: dict | list[dict], on_conflict: str = "id") -> bool:
        """POST with upsert (merge on conflict)."""
        url = f"{self.url}/{table}"
        try:
            headers = self.headers.copy()
            headers["Prefer"] = "resolution=merge-duplicates,return=minimal"
            resp = requests.post(url, json=data, headers=headers, timeout=15)
            resp.raise_for_status()
            return True
        except Exception as e:
            log.warning(f"Supabase UPSERT {table} failed: {e}")
            try:
                log.warning(f"  Response body: {resp.text[:500]}")
            except Exception:
                pass
            return False

    def update(self, table: str, filters: dict, data: dict) -> bool:
        """PATCH to update rows matching filters."""
        url = f"{self.url}/{table}"
        # Build filter query string: key=eq.value
        filter_parts = []
        for k, v in filters.items():
            if isinstance(v, bool):
                filter_parts.append(f"{k}=eq.{str(v).lower()}")
            else:
                filter_parts.append(f"{k}=eq.{v}")
        filter_query = "&".join(filter_parts)

        try:
            headers = self.headers.copy()
            headers["Prefer"] = "return=minimal"
            full_url = f"{url}?{filter_query}" if filter_query else url
            resp = requests.patch(full_url, json=data, headers=headers, timeout=15)
            resp.raise_for_status()
            return True
        except Exception as e:
            log.warning(f"Supabase UPDATE {table} failed: {e}")
            try:
                log.warning(f"  Response body: {resp.text[:500]}")
                log.warning(f"  PATCH payload: {json.dumps(data)[:500]}")
                log.warning(f"  PATCH URL: {full_url}")
            except Exception:
                pass
            return False

    def get_by_domain(self, domain: str) -> Optional[dict]:
        """Get portfolio company by domain."""
        url = f"{self.url}/vc_portfolio_companies?domain=eq.{domain}&limit=1"
        try:
            resp = requests.get(url, headers=self.headers, timeout=15)
            resp.raise_for_status()
            data = resp.json()
            return data[0] if data else None
        except Exception as e:
            log.debug(f"GET company by domain failed: {e}")
            return None

    def get_by_url(self, url_val: str, table: str = "vc_jobs") -> Optional[dict]:
        """Get job by URL."""
        url = f"{self.url}/{table}?url=eq.{url_val}&limit=1"
        try:
            resp = requests.get(url, headers=self.headers, timeout=15)
            resp.raise_for_status()
            data = resp.json()
            return data[0] if data else None
        except Exception as e:
            log.debug(f"GET by url failed: {e}")
            return None


# Create global client
sb = SupabaseClient()

# ─────────────────────────────────────────────────────────────────────
# TARGET ROLES
# ─────────────────────────────────────────────────────────────────────

TARGET_TITLES = [
    "CFO",
    "Chief of Staff",
    "COO",
    "CRO",
    "Director of Finance",
    "Director of Technical Accounting",
    "Head of Accounting Operations",
    "Head of Finance",
    "Head of Finance and Operations",
    "Head of FP&A",
    "Head of Operations",
    "Head of Operations and Finance",
    "Head of Ops and Finance",
    "Head of Revenue Cycle Management",
    "Head of Strategic Finance",
    "SVP of Finance",
    "SVP of Finance and Operations",
    "SVP of Operations",
    "Vice President of Revenue Operations",
    "VP of Operations",
]
_TITLE_LOWER = [t.lower() for t in TARGET_TITLES]

TARGET_STAGES = {
    "series a", "series b", "series c",
}
EXCLUDE_STAGES = {
    "pre-seed", "seed", "pre seed", "seed stage", "angel",
    "series d", "series e", "series f", "series g",
    "growth", "late stage", "ipo", "public",
}

MIN_SALARY = 200_000

OUTPUT_PREFIX = "vc_jobs"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/121.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

# ─────────────────────────────────────────────────────────────────────
# VC CONFIGURATION
# ─────────────────────────────────────────────────────────────────────

VC_LIST = [
    {
        "name": "Greycroft",
        "portfolio_url": "https://www.greycroft.com/investments/",
        "contact": None,
        "js_required": True,
        "notes": "Full alpha list at /investments/; JS-rendered React app",
    },
    {
        "name": "Point72 Ventures",
        "portfolio_url": "https://p72.vc/portfolio/",
        "contact": "Chris Jackson",
        "js_required": True,
    },
    {
        "name": "Canvas Ventures",
        "portfolio_url": "https://www.canvas.vc/portfolio",
        "contact": None,
        "js_required": True,
        "notes": "Series A/B fintech, digital health, AI",
    },
    {
        "name": "Upfront Ventures",
        "portfolio_url": "https://upfront.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "SignalFire",
        "portfolio_url": "https://www.signalfire.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Andreessen Horowitz",
        "portfolio_url": "https://a16z.com/portfolio",
        "contact": None,
        "js_required": True,
        "notes": "Very large portfolio; use stage filters on page",
    },
    {
        "name": "Redpoint Ventures",
        "portfolio_url": "https://www.redpoint.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Bain Capital Ventures",
        "portfolio_url": "https://www.baincapitalventures.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Renegade Partners",
        "portfolio_url": "https://www.renegadepartners.com/portfolio",
        "contact": None,
        "js_required": True,
        "notes": "Series A/B focus; post-PMF companies",
    },
    {
        "name": "Mayfield",
        "portfolio_url": "https://www.mayfield.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Gradient Ventures",
        "portfolio_url": "https://www.gradient.com/portfolio/",
        "contact": None,
        "js_required": True,
        "notes": "Google's AI fund",
    },
    {
        "name": "Quiet Capital",
        "portfolio_url": "https://quiet.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Scale Venture Partners",
        "portfolio_url": "https://www.scalevp.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "The Westly Group",
        "portfolio_url": "https://westlygroup.com/portfolio/",
        "contact": None,
        "js_required": False,
        "notes": "Energy, mobility, industrial tech, cybersecurity",
    },
    {
        "name": "Lightspeed Venture Partners",
        "portfolio_url": "https://lsvp.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Kindred Ventures",
        "portfolio_url": "https://kindredvc.com/companies",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Venrock",
        "portfolio_url": "https://www.venrock.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "S3 Ventures",
        "portfolio_url": "https://s3.vc/portfolio",
        "contact": None,
        "js_required": False,
        "notes": "Texas-focused VC",
    },
    {
        "name": "SemperVirens Venture Capital",
        "portfolio_url": "https://www.sempervirensvc.com/portfolio",
        "contact": None,
        "js_required": True,
        "notes": "Health, wealth, work tech",
    },
    {
        "name": "Sageview Capital",
        "portfolio_url": "https://www.sageviewcapital.com/portfolio-category/current-investments/",
        "contact": None,
        "js_required": False,
        "notes": "Growth equity; some early-stage; 4-5 investments/yr",
    },
    {
        "name": "Peak XV Partners",
        "portfolio_url": "https://www.peakxv.com/portfolio",
        "contact": None,
        "js_required": True,
        "notes": "Formerly Sequoia India/SEA",
    },
    {
        "name": "Sierra Ventures",
        "portfolio_url": "https://www.sierraventures.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "ICONIQ Growth",
        "portfolio_url": "https://iconiqcapital.com/growth/portfolio",
        "contact": None,
        "js_required": True,
        "notes": "Primarily growth/late stage; filter carefully",
    },
    {
        "name": "Bessemer Venture Partners",
        "portfolio_url": "https://www.bvp.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Canapi Ventures",
        "portfolio_url": "https://www.canapi.com/portfolio",
        "contact": None,
        "js_required": True,
        "notes": "Fintech and banking focus",
    },
    {
        "name": "Menlo Ventures",
        "portfolio_url": "https://menlovc.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "General Catalyst",
        "portfolio_url": "https://www.generalcatalyst.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Footwork",
        "portfolio_url": "https://www.footwork.vc/",
        "contact": "Rachel Coffman",
        "js_required": True,
        "notes": "Consumer tech; Seed/Series A; portfolio on homepage",
    },
    {
        "name": "Off Leash Capital",
        "portfolio_url": "https://offleash.capital/portfolio",
        "contact": "Gina del Vecchio",
        "js_required": False,
        "notes": "Pet health niche; small fund",
    },
    {
        "name": "Village Global",
        "portfolio_url": "https://www.villageglobal.vc/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Coastanoa Ventures",
        "portfolio_url": "https://coastanoa.com/portfolio",
        "contact": None,
        "js_required": True,
    },
    {
        "name": "Susa Ventures",
        "portfolio_url": "https://www.susaventures.com/portfolio/full-portfolio",
        "contact": None,
        "js_required": False,
        "notes": "150+ companies; full portfolio list available",
    },
    {
        "name": "Ascension Ventures",
        "portfolio_url": "https://ascensionventures.org/our-portfolio/",
        "contact": "John Kuelper",
        "js_required": False,
        "notes": "Healthcare tech; Seed–Series B",
    },
    {
        "name": "Greck VC",
        "portfolio_url": "https://greck.vc/",
        "contact": "Jack Greco",
        "js_required": False,
        "notes": "Angel investor; personal portfolio",
    },
    {
        "name": "Capital 49",
        "portfolio_url": "https://www.capital49.com/portfolio",
        "contact": "Chris Cheng",
        "js_required": True,
        "notes": "Fintech/SaaS; small early-stage fund",
    },
    {
        "name": "Virta Ventures",
        "portfolio_url": "https://www.virtaventures.co/portfolio",
        "contact": "Russell Sprole",
        "js_required": False,
        "notes": "Pre-seed/seed climate tech",
    },
    {
        "name": "Joyance Partners",
        "portfolio_url": "https://www.joyancepartners.com/portfolio",
        "contact": "Bradley Welch",
        "js_required": True,
        "notes": "Health, consumer; pre-seed to Series A; 188 companies",
    },
    {
        "name": "Live Oak Ventures",
        "portfolio_url": "https://liveoak.vc/portfolio/",
        "contact": None,
        "js_required": False,
        "notes": "Texas-focused; $500M AUM",
    },
    {
        "name": "JMI Equity",
        "portfolio_url": "https://www.jmi.com/companies/",
        "contact": "Matt Cameron",
        "js_required": True,
        "notes": "Growth equity software; many Series D+; check stages carefully",
    },
    {
        "name": "Felicis Ventures",
        "portfolio_url": "https://www.felicis.com/portfolio",
        "contact": "Dasha Maggio",
        "js_required": True,
    },
    {
        "name": "Underscore VC",
        "portfolio_url": "https://underscore.vc/portfolio",
        "contact": "Brian Devaney",
        "js_required": True,
        "notes": "Boston; enterprise and vertical software",
    },
]

# ─────────────────────────────────────────────────────────────────────
# FILTERING HELPERS
# ─────────────────────────────────────────────────────────────────────

def title_matches(title: str) -> bool:
    """Return True if the job title matches any target role."""
    t = title.lower().strip()

    # Reject anything that looks like page content rather than a job title:
    # real job titles are short and don't contain URLs, cookie language, etc.
    if len(t) > 100:
        return False
    junk_phrases = [
        'cookie', 'privacy policy', 'gdpr', 'javascript:', 'visit site',
        'read more', 'learn more', 'sign up', 'log in', 'subscribe',
    ]
    for phrase in junk_phrases:
        if phrase in t:
            return False

    # Word-boundary match (not bare substring) to avoid "cfos", "office of cfo", etc.
    patterns = [
        r'\bcfo\b', r'\bcoo\b', r'\bcro\b',
        r'\bchief of staff\b',
        r'\bchief financial officer\b',
        r'\bchief operating officer\b',
        r'\bchief revenue officer\b',
        r'\b(vp|vice president) of (finance|operations|ops|revenue operations)\b',
        r'\b(svp|senior vice president) of (finance|operations|ops)\b',
        r'\bdirector of (finance|technical accounting|accounting)\b',
        r'\bhead of (finance|operations|ops|fp&a|strategic finance|'
        r'revenue cycle|accounting operations|revenue cycle management)\b',
        r'\bhead of finance and operations\b',
        r'\bhead of ops and finance\b',
    ]
    for pat in patterns:
        if re.search(pat, t):
            return True
    return False


def is_us_location(location: str) -> bool:
    """Return True if the location is US-based or unspecified."""
    if not location or not location.strip():
        return True  # include unspecified (could be remote)

    loc = location.lower()

    non_us_keywords = [
        'london', ' uk', 'united kingdom', 'england', 'canada', 'toronto',
        'vancouver', 'india', 'bangalore', 'bengaluru', 'mumbai', 'hyderabad',
        'australia', 'sydney', 'melbourne', 'germany', 'berlin', 'france',
        'paris', 'singapore', 'hong kong', 'mexico', 'brazil', 'netherlands',
        'amsterdam', 'sweden', 'stockholm', 'ireland', 'dublin', 'israel',
        'tel aviv', 'spain', 'madrid', 'barcelona', 'poland', 'warsaw',
        'japan', 'tokyo', 'korea', 'seoul', 'china', 'beijing', 'shanghai',
    ]
    for kw in non_us_keywords:
        if kw in loc:
            return False

    return True  # default include


def salary_qualifies(salary_text: str) -> bool:
    """Return True if salary meets minimum or if salary is not listed."""
    if not salary_text or not salary_text.strip():
        return True

    text = salary_text.replace(',', '').lower()
    matches = re.findall(r'\$?(\d+(?:\.\d+)?)([km]?)', text)

    values = []
    for num_str, suffix in matches:
        val = float(num_str)
        if suffix == 'k':
            val *= 1_000
        elif suffix == 'm':
            val *= 1_000_000
        if val >= 10_000:  # plausible annual salary
            values.append(int(val))

    if not values:
        return True  # can't parse, include it

    return min(values) >= MIN_SALARY


def stage_qualifies(stage: str) -> bool:
    """True only for Series A/B/C. Unknown/unconfirmed stages are excluded."""
    if not stage or stage.lower().strip() in ("", "unknown", "not specified"):
        return False
    s = stage.lower().strip()
    for ex in EXCLUDE_STAGES:
        if ex in s:
            return False
    for tgt in TARGET_STAGES:
        if tgt in s:
            return True
    return False  # unknown stage: exclude


# ─────────────────────────────────────────────────────────────────────
# URL / DOMAIN HELPERS
# ─────────────────────────────────────────────────────────────────────

def get_domain(url: str) -> str:
    parsed = urlparse(url)
    return parsed.netloc.lstrip("www.")


def safe_get(url: str, timeout: int = 15) -> Optional[requests.Response]:
    try:
        resp = requests.get(url, headers=HEADERS, timeout=timeout, allow_redirects=True)
        resp.raise_for_status()
        return resp
    except Exception as e:
        log.debug(f"GET {url} failed: {e}")
        return None


# ─────────────────────────────────────────────────────────────────────
# CAREERS PAGE DETECTION
# ─────────────────────────────────────────────────────────────────────

CAREERS_PATHS = [
    "/careers", "/jobs", "/open-roles", "/work-with-us", "/join-us",
    "/join", "/hiring", "/openings", "/company/careers", "/about/careers",
    "/careers/", "/jobs/", "/work-here", "/careers/open-positions",
]

# ATS detection: (ats_type, regex, slug_group)
ATS_PATTERNS = [
    ("greenhouse",  r"boards\.greenhouse\.io/([^/\s\"'?#]+)", 1),
    ("greenhouse",  r"job-boards\.greenhouse\.io/([^/\s\"'?#]+)", 1),
    ("greenhouse",  r"greenhouse\.io/embed/job_board\?for=([^&\s\"']+)", 1),
    ("lever",       r"jobs\.lever\.co/([^/\s\"'?#]+)", 1),
    ("ashby",       r"jobs\.ashbyhq\.com/([^/\s\"'?#]+)", 1),
    ("workday",     r"([a-zA-Z0-9-]+)\.wd\d+\.myworkdayjobs\.com", 1),
    ("bamboohr",    r"([a-zA-Z0-9-]+)\.bamboohr\.com/careers", 1),
    ("rippling",    r"app\.rippling\.com/jobs/([^/\s\"'?#]+)", 1),
    ("smartrec",    r"careers\.smartrecruiters\.com/([^/\s\"'?#]+)", 1),
    ("jobvite",     r"jobs\.jobvite\.com/([^/\s\"'?#]+)", 1),
    ("breezy",      r"([a-zA-Z0-9-]+)\.breezy\.hr/p/", 1),
    ("dover",       r"app\.dover\.com/apply/([^/\s\"'?#]+)", 1),
    ("wellfound",   r"wellfound\.com/company/([^/\s\"'?#]+)/jobs", 1),
]


def detect_ats(html: str, base_url: str) -> tuple[Optional[str], Optional[str], Optional[str]]:
    """
    Detect which ATS a company uses.
    Returns (ats_type, slug, direct_careers_url).
    """
    content = html + " " + base_url
    for ats_type, pattern, group in ATS_PATTERNS:
        m = re.search(pattern, content, re.IGNORECASE)
        if m:
            slug = m.group(group) if group <= m.lastindex or m.lastindex is None else None
            # Clean slug
            if slug:
                slug = slug.rstrip("/").lower()

            if ats_type == "greenhouse":
                direct = f"https://boards.greenhouse.io/{slug}"
            elif ats_type == "lever":
                direct = f"https://jobs.lever.co/{slug}"
            elif ats_type == "ashby":
                direct = f"https://jobs.ashbyhq.com/{slug}"
            else:
                direct = None

            return ats_type, slug, direct

    return None, None, None


def find_careers_url(company_domain: str) -> Optional[str]:
    """
    Try common paths and homepage link scan to find a careers page.
    Returns the careers URL or None.
    """
    if not company_domain:
        return None

    base = f"https://{company_domain}"

    # 1. Try common paths
    for path in CAREERS_PATHS:
        url = base + path
        resp = safe_get(url, timeout=8)
        if resp and resp.status_code == 200 and len(resp.text) > 300:
            soup = BeautifulSoup(resp.text, "lxml")
            text = soup.get_text().lower()
            job_signals = [
                "open role", "open position", "join our team",
                "job opening", "career opportunity", "we're hiring",
                "apply now", "view openings",
            ]
            if any(sig in text for sig in job_signals):
                return url
            # Also check if page has ATS embed
            ats_type, slug, direct = detect_ats(resp.text, url)
            if ats_type:
                return direct or url

    # 2. Scan homepage for careers links
    resp = safe_get(base, timeout=10)
    if resp:
        soup = BeautifulSoup(resp.text, "lxml")
        careers_kw = ["career", "job", "hiring", "join us", "work with us", "open role"]
        for link in soup.find_all("a", href=True):
            href = link["href"].lower()
            link_text = link.get_text().lower()
            if any(kw in href or kw in link_text for kw in careers_kw):
                full_url = urljoin(base, link["href"])
                # Skip social media
                if any(s in full_url for s in ["linkedin", "twitter", "facebook", "instagram"]):
                    continue
                return full_url

    return None


# ─────────────────────────────────────────────────────────────────────
# JOB SCRAPERS — ATS-SPECIFIC
# ─────────────────────────────────────────────────────────────────────

def scrape_greenhouse(slug: str) -> list[dict]:
    """Use Greenhouse public API."""
    url = f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs?content=true"
    resp = safe_get(url)
    if not resp:
        return []
    try:
        data = resp.json()
        jobs = []
        for j in data.get("jobs", []):
            title = j.get("title", "")

            # Location: prefer offices list, fall back to location field
            location = ", ".join(
                loc.get("name", "") for loc in j.get("offices", []) if loc.get("name")
            ) or j.get("location", {}).get("name", "")

            job_url = j.get("absolute_url", "")

            # Salary from metadata fields
            salary_text = ""
            for meta in j.get("metadata", []):
                name_lower = meta.get("name", "").lower()
                if "salary" in name_lower or "comp" in name_lower or "pay" in name_lower:
                    salary_text = str(meta.get("value") or "")

            # Also check content for salary mention
            content = j.get("content", "") or ""
            if not salary_text:
                m = re.search(
                    r'\$[\d,]+\s*[-–]\s*\$[\d,]+|\$[\d,]+[kK]?\s*[-–]\s*\$[\d,]+[kK]?',
                    content
                )
                if m:
                    salary_text = m.group(0)

            jobs.append({
                "title": title,
                "location": location,
                "url": job_url,
                "salary_text": salary_text,
            })
        return jobs
    except Exception as e:
        log.debug(f"Greenhouse parse error ({slug}): {e}")
        return []


def scrape_lever(slug: str) -> list[dict]:
    """Use Lever public API."""
    url = f"https://api.lever.co/v0/postings/{slug}?mode=json"
    resp = safe_get(url)
    if not resp:
        return []
    try:
        data = resp.json()
        jobs = []
        for j in data:
            title = j.get("text", "")
            cats = j.get("categories", {})
            location = cats.get("location", "") or cats.get("allLocations", [""])[0]
            job_url = j.get("hostedUrl", "")

            salary_text = ""
            for lst in j.get("lists", []):
                lst_text = lst.get("text", "").lower()
                if "salary" in lst_text or "compensation" in lst_text or "pay" in lst_text:
                    salary_text = BeautifulSoup(lst.get("content", ""), "lxml").get_text(" ")

            # Check plain text content
            if not salary_text:
                plain = j.get("description", "") or j.get("descriptionPlain", "") or ""
                m = re.search(
                    r'\$[\d,]+\s*[-–]\s*\$[\d,]+|\$[\d,]+[kK]?\s*[-–]\s*\$[\d,]+[kK]?',
                    plain
                )
                if m:
                    salary_text = m.group(0)

            jobs.append({
                "title": title,
                "location": location,
                "url": job_url,
                "salary_text": salary_text,
            })
        return jobs
    except Exception as e:
        log.debug(f"Lever parse error ({slug}): {e}")
        return []


def scrape_ashby(slug: str) -> list[dict]:
    """Use Ashby HQ public GraphQL endpoint."""
    url = "https://jobs.ashbyhq.com/api/non-user-graphql"
    query = {
        "operationName": "ApiJobBoardWithTeams",
        "variables": {"organizationHostedJobsPageName": slug},
        "query": """
            query ApiJobBoardWithTeams($organizationHostedJobsPageName: String!) {
              jobBoard: jobBoardWithTeams(
                organizationHostedJobsPageName: $organizationHostedJobsPageName
              ) {
                jobPostings {
                  id
                  title
                  isRemote
                  locationName
                  compensationTierSummary
                  externalLink
                  publishedDate
                }
              }
            }
        """,
    }
    try:
        resp = requests.post(url, json=query, headers=HEADERS, timeout=15)
        data = resp.json()
        postings = (
            data.get("data", {})
                .get("jobBoard", {})
                .get("jobPostings", [])
        ) or []
        jobs = []
        for p in postings:
            location = p.get("locationName", "")
            if p.get("isRemote"):
                location = "Remote" + (f", {location}" if location else "")
            job_url = (
                p.get("externalLink")
                or f"https://jobs.ashbyhq.com/{slug}/{p.get('id', '')}"
            )
            jobs.append({
                "title": p.get("title", ""),
                "location": location,
                "url": job_url,
                "salary_text": p.get("compensationTierSummary") or "",
            })
        return jobs
    except Exception as e:
        log.debug(f"Ashby parse error ({slug}): {e}")
        return []


def scrape_generic(careers_url: str) -> list[dict]:
    """
    Generic HTML scraper for companies without a known ATS.
    Looks for job title + link pairs using common structural patterns.
    """
    resp = safe_get(careers_url)
    if not resp:
        return []

    soup = BeautifulSoup(resp.text, "lxml")
    jobs = []
    seen = set()

    # Ranked list of selectors that tend to wrap individual job listings
    selectors = [
        "[class*='job-item']", "[class*='job-listing']", "[class*='job-posting']",
        "[class*='opening']", "[class*='position']", "[class*='role']",
        "[class*='career-item']", "li[class*='job']", "tr[class*='job']",
        "[data-job]", "[data-position]",
    ]
    containers = []
    for sel in selectors:
        found = soup.select(sel)
        if found:
            containers.extend(found)

    if not containers:
        # Fallback: anchors whose text looks like a job title (skip nav/legal links)
        containers = [
            a for a in soup.find_all("a", href=True)
            if not re.search(
                r'cookie|privacy|terms|gdpr|legal|policy|javascript:|#',
                (a.get("href", "") + a.get_text()).lower()
            )
        ]

    # URL patterns that indicate non-job pages
    junk_url_patterns = re.compile(
        r'cookie|privacy|terms|legal|gdpr|javascript:|#cookie|#privacy'
        r'|/blog/|/press/|/news/|/about|/contact|/team|linkedin\.com/in/',
        re.I
    )

    for item in containers:
        if item.name == "a":
            title = item.get_text(" ", strip=True)
            href = item.get("href", "")
        else:
            h_tag = item.find(["h2", "h3", "h4", "h5", "strong"])
            title = h_tag.get_text(" ", strip=True) if h_tag else item.get_text(" ", strip=True)[:100]
            a_tag = item.find("a", href=True)
            href = a_tag["href"] if a_tag else ""

        if not title or len(title) < 5 or len(title) > 100 or title in seen:
            continue

        # Skip junk URLs
        full_url = urljoin(careers_url, href) if href else ""
        if junk_url_patterns.search(full_url):
            continue

        seen.add(title)

        job_url = urljoin(careers_url, href) if href else careers_url

        # Try to find location in the same container
        loc_tags = item.find_all(["span", "p", "div"], class_=re.compile(r"loc|location|office", re.I))
        location = loc_tags[0].get_text(" ", strip=True) if loc_tags else ""

        jobs.append({
            "title": title,
            "location": location,
            "url": job_url,
            "salary_text": "",
        })

    return jobs


def get_jobs_for_company(co: dict) -> list[dict]:
    """Route to correct job scraper based on detected ATS."""
    ats_type = co.get("ats_type")
    slug = co.get("ats_slug")
    careers_url = co.get("careers_url", "")

    if ats_type == "greenhouse" and slug:
        return scrape_greenhouse(slug)
    if ats_type == "lever" and slug:
        return scrape_lever(slug)
    if ats_type == "ashby" and slug:
        return scrape_ashby(slug)
    if careers_url:
        return scrape_generic(careers_url)
    return []


# ─────────────────────────────────────────────────────────────────────
# FUNDING STAGE LOOKUP (Crunchbase public autocomplete)
# ─────────────────────────────────────────────────────────────────────

def lookup_stage_crunchbase(company_name: str) -> Optional[str]:
    """
    Query Crunchbase's public autocomplete API for last known funding stage.
    Returns e.g. 'series_b', 'seed', etc.  or None on failure.
    """
    url = "https://www.crunchbase.com/v4/data/autocompletes"
    params = {
        "query": company_name,
        "collection_ids": "organizations",
        "limit": 3,
    }
    try:
        resp = requests.get(url, params=params, headers=HEADERS, timeout=10)
        for entity in resp.json().get("entities", []):
            props = entity.get("properties", {})
            stage = (
                props.get("funding_stage", {}).get("value")
                or props.get("last_funding_type", {}).get("value")
            )
            if stage:
                return stage.lower().replace("_", " ")
    except Exception:
        pass
    return None


# ─────────────────────────────────────────────────────────────────────
# VC PORTFOLIO SCRAPING
# ─────────────────────────────────────────────────────────────────────

def scrape_vc_portfolio_static(vc: dict) -> list[dict]:
    """
    Scrape a static VC portfolio page.
    Returns [{company_name, domain, stage, detail_url}].
    """
    url = vc["portfolio_url"]
    resp = safe_get(url)
    if not resp:
        log.warning(f"  Could not fetch {url}")
        return []

    soup = BeautifulSoup(resp.text, "lxml")
    vc_domain = get_domain(url)
    seen_domains = set()
    companies = []

    skip_domains = {
        "twitter.com", "x.com", "linkedin.com", "facebook.com",
        "instagram.com", "youtube.com", "crunchbase.com", "pitchbook.com",
        "medium.com", "techcrunch.com",
    }

    junk_names = {
        "exit", "visit site", "visit", "view", "learn more",
        "read more", "lp login", "sign in", "log in", "sign up",
        "contact", "contact us", "about", "about us", "home",
        "back to top", "subscribe", "newsletter", "blog",
        "portfolio", "team", "careers", "press", "news",
        "privacy", "terms", "cookie", "menu", "close",
        "view open roles here.", "our portfolio companies.",
        "portfolio jobs", "see all", "view all", "show more",
        "load more", "explore", "apply now",
    }
    seen_names = set()

    for a in soup.find_all("a", href=True):
        text = a.get_text(" ", strip=True)
        if not text or len(text) < 2 or len(text) > 80:
            continue
        if text.lower().rstrip(".") in junk_names:
            continue
        if len(text.split()) > 8:
            continue

        full_url = urljoin(url, a["href"])
        domain = get_domain(full_url)

        if not domain or domain == vc_domain:
            continue
        if domain in skip_domains:
            continue
        if domain in seen_domains:
            continue
        if any(s in full_url.lower() for s in ["mailto:", "tel:", "#"]):
            continue

        name_key = text.lower().strip()
        if name_key in seen_names:
            continue

        seen_domains.add(domain)
        seen_names.add(name_key)
        companies.append({
            "company_name": text,
            "domain": domain,
            "stage": None,
            "detail_url": full_url,
        })

    return companies


async def scrape_vc_portfolio_playwright(vc: dict) -> list[dict]:
    """
    Playwright-based scraper for JS-rendered VC portfolio pages.
    Uses multiple extraction strategies:
      1. Intercept XHR/fetch responses that may contain portfolio data
      2. Scroll to bottom to trigger lazy loading
      3. Extract from links, cards, grid items, and logo containers
    Falls back to static scraper if Playwright is not installed.
    """
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        log.warning(
            f"  Playwright not installed — using static fallback for {vc['name']}.\n"
            "  Install with: pip install playwright && playwright install chromium"
        )
        return scrape_vc_portfolio_static(vc)

    url = vc["portfolio_url"]
    vc_domain = get_domain(url)
    skip_domains = {
        "twitter.com", "x.com", "linkedin.com", "facebook.com",
        "instagram.com", "youtube.com", "crunchbase.com", "pitchbook.com",
        "medium.com", "techcrunch.com", "github.com", "google.com",
        "apple.com", "apps.apple.com", "play.google.com",
    }
    companies = []
    api_companies = []  # companies found via intercepted API responses

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        page = await browser.new_page(
            user_agent=HEADERS["User-Agent"],
            viewport={"width": 1280, "height": 900},
        )

        # Strategy 1: Intercept network responses for portfolio API data
        async def handle_response(response):
            try:
                content_type = response.headers.get("content-type", "")
                if "json" not in content_type:
                    return
                if response.status != 200:
                    return
                body = await response.text()
                if len(body) < 100 or len(body) > 5_000_000:
                    return
                data = json.loads(body)
                _extract_companies_from_api(data, api_companies, vc_domain, skip_domains)
            except Exception:
                pass

        page.on("response", handle_response)

        try:
            await page.goto(url, wait_until="networkidle", timeout=45_000)
            await page.wait_for_timeout(2_000)

            # Strategy 2: Scroll to bottom to trigger lazy loading
            await _scroll_to_bottom(page)
            await page.wait_for_timeout(2_000)

            # Strategy 3: Extract from DOM — links, cards, grid items
            links_data = await page.evaluate("""
                () => {
                    const results = [];
                    const seen = new Set();

                    // Helper: extract domain from URL
                    function getDomain(url) {
                        try { return new URL(url).hostname.replace(/^www\\./, ''); }
                        catch { return null; }
                    }

                    // Helper: find stage text near an element
                    function findStage(el) {
                        const container = el.closest('[class]') || el.parentElement;
                        if (!container) return null;
                        const text = (container.innerText || '').toLowerCase();
                        const m = text.match(
                            /\\b(pre-?seed|seed|series\\s*[a-d])\\b/i
                        );
                        return m ? m[1].trim() : null;
                    }

                    // Pass 1: External links (original approach, still valuable)
                    document.querySelectorAll('a[href]').forEach(a => {
                        const text = (a.innerText || a.textContent || '').trim();
                        const href = a.href;
                        if (!text || text.length < 2 || text.length > 80) return;
                        const domain = getDomain(href);
                        if (!domain || seen.has(domain)) return;
                        seen.add(domain);
                        results.push({
                            text, href, domain,
                            stage: findStage(a),
                            source: 'link'
                        });
                    });

                    // Pass 2: Cards / grid items that may contain company info
                    // Look for repeated sibling elements (portfolio grid pattern)
                    const cardSelectors = [
                        '[class*="portfolio"] [class*="item"]',
                        '[class*="portfolio"] [class*="card"]',
                        '[class*="company"]', '[class*="startup"]',
                        '[class*="grid"] > div', '[class*="grid"] > a',
                        '[class*="logo"]', '[class*="brand"]',
                        '[data-company]', '[data-name]',
                    ];
                    for (const sel of cardSelectors) {
                        document.querySelectorAll(sel).forEach(card => {
                            // Get company name from heading, alt text, or card text
                            const heading = card.querySelector('h2,h3,h4,h5,strong,[class*="name"],[class*="title"]');
                            const img = card.querySelector('img[alt]');
                            let name = '';
                            if (heading && heading.innerText) name = heading.innerText.trim();
                            else if (img && img.alt && img.alt.length > 1 && img.alt.length < 80) name = img.alt.trim();
                            else if (card.innerText) {
                                const t = card.innerText.trim();
                                if (t.length > 1 && t.length < 80 && !t.includes('\\n')) name = t;
                            }
                            if (!name || name.length < 2) return;

                            // Get URL from link in card or card itself
                            const link = card.tagName === 'A' ? card : card.querySelector('a[href]');
                            const href = link ? link.href : '';
                            const domain = href ? getDomain(href) : null;

                            if (domain && !seen.has(domain)) {
                                seen.add(domain);
                                results.push({
                                    text: name, href, domain,
                                    stage: findStage(card),
                                    source: 'card'
                                });
                            } else if (!domain && name.length > 2) {
                                // Company name without link — still useful
                                results.push({
                                    text: name, href: '', domain: null,
                                    stage: findStage(card),
                                    source: 'card_nolink'
                                });
                            }
                        });
                    }

                    return results;
                }
            """)

            # Junk text patterns to skip (nav elements, exit labels, etc.)
            junk_names = {
                "exit", "visit site", "visit", "view", "learn more",
                "read more", "lp login", "sign in", "log in", "sign up",
                "contact", "contact us", "about", "about us", "home",
                "back to top", "subscribe", "newsletter", "blog",
                "portfolio", "team", "careers", "press", "news",
                "privacy", "terms", "cookie", "menu", "close",
                "view open roles here.", "our portfolio companies.",
                "portfolio jobs", "see all", "view all", "show more",
                "load more", "explore", "apply now",
            }

            seen_domains = set()
            seen_names = set()
            for item in links_data:
                text = (item.get("text") or "").strip()
                href = item.get("href") or ""
                stage = item.get("stage")
                domain = item.get("domain") or (get_domain(href) if href else None)

                if not text or len(text) < 2 or len(text) > 80:
                    continue
                # Skip junk nav/label text
                if text.lower().rstrip(".") in junk_names:
                    continue
                # Skip if text looks like a sentence or description (has too many words)
                if len(text.split()) > 8:
                    continue
                # Must have a domain; entries without one are unusable
                if not domain:
                    continue
                if domain == vc_domain:
                    continue
                if domain in skip_domains:
                    continue
                if domain in seen_domains:
                    continue
                if any(s in href.lower() for s in ["mailto:", "tel:", "javascript:"]):
                    continue
                # Skip duplicate company names (catches same company from different elements)
                name_key = text.lower().strip()
                if name_key in seen_names:
                    continue

                seen_domains.add(domain)
                seen_names.add(name_key)

                companies.append({
                    "company_name": text,
                    "domain": domain,
                    "stage": stage,
                    "detail_url": href,
                })

        except Exception as e:
            log.error(f"  Playwright error on {url}: {e}")
        finally:
            await browser.close()

    # Merge API-discovered companies (higher confidence)
    seen_domains = {c["domain"] for c in companies if c.get("domain")}
    for ac in api_companies:
        if ac.get("domain") and ac["domain"] not in seen_domains:
            companies.append(ac)
            seen_domains.add(ac["domain"])

    return companies


async def _scroll_to_bottom(page, max_scrolls: int = 10):
    """Scroll page to bottom incrementally to trigger lazy loading."""
    for _ in range(max_scrolls):
        prev_height = await page.evaluate("document.body.scrollHeight")
        await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
        await page.wait_for_timeout(800)
        new_height = await page.evaluate("document.body.scrollHeight")
        if new_height == prev_height:
            break


def _extract_companies_from_api(
    data, results: list, vc_domain: str, skip_domains: set
):
    """
    Recursively search JSON API response data for portfolio company info.
    Many VC sites fetch portfolio data from a CMS API (Contentful, Sanity, etc.).
    """
    if isinstance(data, list):
        for item in data:
            _extract_companies_from_api(item, results, vc_domain, skip_domains)
    elif isinstance(data, dict):
        # Heuristic: dict with name/company/title + url/website/domain fields
        name_keys = {"name", "company", "company_name", "title", "companyName"}
        url_keys = {"url", "website", "domain", "href", "link", "websiteUrl", "companyUrl"}

        name_val = None
        url_val = None
        for k, v in data.items():
            if k.lower() in {nk.lower() for nk in name_keys} and isinstance(v, str) and 2 < len(v) < 80:
                name_val = v
            if k.lower() in {uk.lower() for uk in url_keys} and isinstance(v, str) and ("." in v or "http" in v):
                url_val = v

        if name_val and url_val:
            if not url_val.startswith("http"):
                url_val = f"https://{url_val}"
            domain = get_domain(url_val)
            if domain and domain != vc_domain and domain not in skip_domains:
                results.append({
                    "company_name": name_val,
                    "domain": domain,
                    "stage": data.get("stage") or data.get("funding_stage"),
                    "detail_url": url_val,
                })
                return  # don't recurse into this object's children

        # Recurse into nested objects/arrays
        for v in data.values():
            if isinstance(v, (dict, list)):
                _extract_companies_from_api(v, results, vc_domain, skip_domains)


async def scan_vc(vc: dict) -> int:
    """Scan one VC portfolio page and upsert results into Supabase."""
    now = datetime.utcnow().isoformat()
    log.info(f"▸ {vc['name']}  →  {vc['portfolio_url']}")

    if vc.get("js_required", True):
        companies = await scrape_vc_portfolio_playwright(vc)
    else:
        companies = scrape_vc_portfolio_static(vc)

    log.info(f"  found {len(companies)} candidates")
    inserted = 0
    failed = 0

    for co in companies:
        name = co["company_name"]
        domain = co["domain"]
        stage = co.get("stage") or None
        # Normalize stage: API intercept may return a list
        if isinstance(stage, list):
            stage = stage[0] if stage else None
        if stage and not isinstance(stage, str):
            stage = str(stage)

        # If stage was detected as excluding, mark accordingly
        if stage and not stage_qualifies(stage):
            log.debug(f"  Skip {name} — stage {stage}")
            continue

        existing = sb.get_by_domain(domain)

        if existing:
            vc_names = existing.get("vc_names") or []
            if vc["name"] not in vc_names:
                vc_names.append(vc["name"])
            sb.update(
                "vc_portfolio_companies",
                {"domain": domain},
                {"vc_names": vc_names, "last_seen": now, "active": True}
            )
        else:
            ok = sb.insert(
                "vc_portfolio_companies",
                {
                    "company": name,
                    "domain": domain,
                    "stage": stage,
                    "vc_names": [vc["name"]],
                    "vc_contact": vc.get("contact"),
                    "active": True,
                    "excluded": False,
                    "enriched": False,
                    "status": "pending",
                    "first_seen": now,
                    "last_seen": now,
                }
            )
            if ok:
                inserted += 1
            else:
                failed += 1

    sb.insert(
        "vc_scan_log",
        {
            "vc_name": vc["name"],
            "scanned_at": now,
            "companies_found": len(companies),
            "status": "ok",
        }
    )
    if failed:
        log.warning(f"  {inserted} inserted, {failed} FAILED to insert")
    else:
        log.info(f"  {inserted} new companies added to Supabase")
    return len(companies)


async def scan_all_vcs():
    log.info(f"Scanning {len(VC_LIST)} VC portfolio pages...")
    for vc in VC_LIST:
        try:
            await scan_vc(vc)
        except Exception as e:
            log.error(f"  Error scanning {vc['name']}: {e}")
        await asyncio.sleep(1.5)


# ─────────────────────────────────────────────────────────────────────
# CAREERS PAGE DISCOVERY PIPELINE
# ─────────────────────────────────────────────────────────────────────

def discover_careers_pages():
    """For approved companies missing a careers URL, attempt to find one."""
    url = f"{SUPABASE_URL}/vc_portfolio_companies"
    params = {
        "careers_url": "is.null",
        "active": "eq.true",
        "excluded": "eq.false",
        "status": "eq.approved",
        "limit": 1000,
    }
    try:
        resp = requests.get(url, headers=sb.headers, params=params, timeout=15)
        resp.raise_for_status()
        rows = resp.json() if resp.text else []
    except Exception as e:
        log.error(f"Failed to fetch companies for careers discovery: {e}")
        return

    log.info(f"Discovering careers pages for {len(rows)} companies...")

    for row in rows:
        domain = row.get("domain")
        company = row.get("company")
        company_id = row.get("id")

        if not domain:
            continue

        careers_url = find_careers_url(domain)

        if not careers_url:
            log.debug(f"  No careers page: {company} ({domain})")
            continue

        # Detect ATS
        resp = safe_get(careers_url, timeout=10)
        ats_type = ats_slug = None
        if resp:
            ats_type, ats_slug, direct = detect_ats(resp.text, careers_url)
            careers_url = direct or careers_url

        sb.update(
            "vc_portfolio_companies",
            {"id": company_id},
            {"careers_url": careers_url, "ats_type": ats_type, "ats_slug": ats_slug}
        )
        log.info(f"  ✓ {company}: {careers_url}  [ATS: {ats_type or 'unknown'}]")
        time.sleep(0.5)


# ─────────────────────────────────────────────────────────────────────
# STAGE ENRICHMENT (Crunchbase fallback)
# ─────────────────────────────────────────────────────────────────────

def enrich_stages():
    """
    For companies missing a stage, attempt Crunchbase lookup.
    Companies found to be Series D+ are marked excluded=True.
    """
    # Get companies with no stage, active
    url = f"{SUPABASE_URL}/vc_portfolio_companies"
    params = {
        "stage": "is.null",
        "active": "eq.true",
        "limit": 1000,
    }
    try:
        resp = requests.get(url, headers=sb.headers, params=params, timeout=15)
        resp.raise_for_status()
        rows = resp.json() if resp.text else []
    except Exception as e:
        log.error(f"Failed to fetch companies for stage enrichment: {e}")
        return

    log.info(f"Enriching funding stages for {len(rows)} companies...")

    for row in rows:
        company_id = row.get("id")
        company = row.get("company")

        if not company:
            continue

        stage = lookup_stage_crunchbase(company)
        if not stage:
            continue

        excluded = not stage_qualifies(stage)
        sb.update(
            "vc_portfolio_companies",
            {"id": company_id},
            {"stage": stage, "excluded": excluded}
        )
        if excluded:
            log.info(f"  Excluding {company} — stage: {stage}")

        time.sleep(0.3)  # polite crawling


# ─────────────────────────────────────────────────────────────────────
# JOB SCANNING PIPELINE
# ─────────────────────────────────────────────────────────────────────

def scan_all_jobs() -> list[dict]:
    """Scan jobs for approved, active portfolio companies."""
    url = f"{SUPABASE_URL}/vc_portfolio_companies"
    params = {
        "active": "eq.true",
        "excluded": "eq.false",
        "status": "eq.approved",
        "careers_url": "not.is.null",
        "limit": 1000,
    }
    try:
        resp = requests.get(url, headers=sb.headers, params=params, timeout=15)
        resp.raise_for_status()
        rows = resp.json() if resp.text else []
    except Exception as e:
        log.error(f"Failed to fetch companies for job scanning: {e}")
        return []

    log.info(f"Scanning jobs for {len(rows)} companies...")
    now = datetime.utcnow().isoformat()
    matching = []

    for co in rows:
        stage = co.get("stage") or ""
        if stage and not stage_qualifies(stage):
            continue

        jobs = get_jobs_for_company(co)
        vc_names = co.get("vc_names") or []

        for job in jobs:
            title = job.get("title", "").strip()
            location = job.get("location", "").strip()
            salary_text = job.get("salary_text", "").strip()
            job_url = job.get("url", "").strip()

            if not title_matches(title):
                continue
            if not is_us_location(location):
                continue
            if not salary_qualifies(salary_text):
                continue

            salary_min = None
            if salary_text:
                vals = re.findall(r"\$?([\d,]+)[kK]?", salary_text.replace(",", ""))
                nums = []
                for v in vals:
                    n = int(v)
                    if "k" in salary_text.lower() and n < 10_000:
                        n *= 1_000
                    if n >= 10_000:
                        nums.append(n)
                salary_min = min(nums) if nums else None

            matching.append({
                "title": title,
                "company": co["company"],
                "stage": stage or "Unknown",
                "vcs_invested": " | ".join(vc_names),
                "location": location or "Not specified",
                "salary": salary_text or "Not listed",
                "url": job_url,
                "first_seen": now,
            })

            # Check if job already exists in vc_jobs
            existing = sb.get_by_url(job_url, "vc_jobs")
            if existing:
                sb.update(
                    "vc_jobs",
                    {"url": job_url},
                    {"last_seen": now, "active": True}
                )
            else:
                sb.insert(
                    "vc_jobs",
                    {
                        "company_id": co["id"],
                        "title": title,
                        "url": job_url,
                        "location": location,
                        "salary_text": salary_text,
                        "salary_min": salary_min,
                        "vc_names": vc_names,
                        "source": "vc_monitor",
                        "first_seen": now,
                        "last_seen": now,
                        "active": True,
                    }
                )

            # Cross-post to the main jobs table so it appears in the dashboard
            existing_main = sb.get_by_url(job_url, "jobs")
            if existing_main:
                sb.update("jobs", {"url": job_url}, {"last_seen": now})
            else:
                sb.insert(
                    "jobs",
                    {
                        "company_name": co["company"],
                        "title": title,
                        "url": job_url,
                        "source": "vc_monitor",
                        "first_seen": now,
                        "last_seen": now,
                        "status": "new",
                    }
                )

        time.sleep(0.5)

    log.info(f"Found {len(matching)} matching jobs")
    return matching


# ─────────────────────────────────────────────────────────────────────
# GITHUB ACTIONS SUMMARY
# ─────────────────────────────────────────────────────────────────────

def write_github_summary(
    vc_scan_results: Optional[dict] = None,
    jobs_found: Optional[list] = None,
):
    """Write a markdown summary to $GITHUB_STEP_SUMMARY if running in GitHub Actions."""
    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if not summary_path:
        return

    lines = ["## VC Monitor Run Summary\n"]

    if vc_scan_results:
        lines.append("### Portfolio Scan")
        lines.append(f"- VCs scanned: **{vc_scan_results.get('vcs_scanned', 0)}**")
        lines.append(f"- New companies found: **{vc_scan_results.get('new_companies', 0)}** (status: pending)")
        lines.append(f"- Existing companies updated: **{vc_scan_results.get('updated', 0)}**")
        lines.append("")

    if jobs_found is not None:
        lines.append("### Job Scan")
        lines.append(f"- Matching jobs found: **{len(jobs_found)}**")
        if jobs_found:
            lines.append("")
            lines.append("| Title | Company | Stage | VCs |")
            lines.append("|-------|---------|-------|-----|")
            for j in jobs_found[:25]:
                lines.append(
                    f"| {j['title']} | {j['company']} | {j['stage']} | {j['vcs_invested']} |"
                )
            if len(jobs_found) > 25:
                lines.append(f"| ... and {len(jobs_found) - 25} more | | | |")
        lines.append("")

    try:
        with open(summary_path, "a") as f:
            f.write("\n".join(lines) + "\n")
    except Exception as e:
        log.debug(f"Could not write GitHub summary: {e}")


# ─────────────────────────────────────────────────────────────────────
# QUICK ATS TEST UTILITY
# ─────────────────────────────────────────────────────────────────────

def test_ats(specs: list[str]):
    """
    Quick-test specific ATS slugs without database.
    Format: ats_type:slug  e.g.  greenhouse:lever  lever:levels  ashby:ashbyhq
    """
    for spec in specs:
        parts = spec.split(":", 1)
        if len(parts) != 2:
            print(f"Bad spec: {spec}  (use ats_type:slug)")
            continue
        ats_type, slug = parts
        print(f"\n{'─'*55}")
        print(f"Testing {ats_type.upper()} slug: {slug}")
        print(f"{'─'*55}")

        if ats_type == "greenhouse":
            jobs = scrape_greenhouse(slug)
        elif ats_type == "lever":
            jobs = scrape_lever(slug)
        elif ats_type == "ashby":
            jobs = scrape_ashby(slug)
        else:
            print(f"Unknown ATS type: {ats_type}")
            continue

        matches = [j for j in jobs if title_matches(j["title"]) and is_us_location(j["location"])]
        print(f"Total jobs: {len(jobs)}  |  Matching roles: {len(matches)}")
        for j in matches:
            print(f"  • {j['title']}  [{j['location']}]  {j['salary_text'] or '(no salary)'}  {j['url']}")


# ─────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────

async def main():
    parser = argparse.ArgumentParser(
        description="VC Portfolio Job Monitor",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--scan-vcs",      action="store_true", help="Scrape VC portfolio pages")
    parser.add_argument("--enrich-stages", action="store_true", help="Lookup funding stages via Crunchbase")
    parser.add_argument("--find-careers",  action="store_true", help="Discover company careers pages (approved companies only)")
    parser.add_argument("--scan-jobs",     action="store_true", help="Scrape job listings (approved companies only)")
    parser.add_argument("--report",        action="store_true", help="Export results from Supabase")
    parser.add_argument("--all",           action="store_true", help="Run full pipeline")
    parser.add_argument("--test-ats",      nargs="+", metavar="TYPE:SLUG",
                        help="Quick-test ATS slugs, e.g. greenhouse:lever  lever:levels")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.test_ats:
        test_ats(args.test_ats)
        return

    if not SUPABASE_KEY:
        log.error("SUPABASE_KEY not set. Export it or pass via environment variable.")
        return

    run_all = args.all or not any(
        [args.scan_vcs, args.enrich_stages, args.find_careers, args.scan_jobs, args.report]
    )

    if args.scan_vcs or run_all:
        await scan_all_vcs()

    if args.enrich_stages or run_all:
        enrich_stages()

    if args.find_careers or run_all:
        discover_careers_pages()

    jobs = []
    if args.scan_jobs or args.report or run_all:
        jobs = scan_all_jobs()

    # Write GitHub Actions summary (no-op if not in Actions)
    write_github_summary(jobs_found=jobs)

    if jobs:
        log.info(f"\nDone! {len(jobs)} matching jobs found.")
    else:
        log.info("\nNo matching jobs found this run.")


if __name__ == "__main__":
    asyncio.run(main())